// Enums del sistema
export enum Role {
  ADMIN = 'ADMIN',
  MARKET = 'MARKET',
  USER = 'USER'
}

export enum EstadoFactura {
  PENDIENTE = 'PENDIENTE',
  PAGADA = 'PAGADA',
  VENCIDA = 'VENCIDA',
  ANULADA = 'ANULADA'
}

export enum EstadoLocal {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  SUSPENDIDO = 'SUSPENDIDO',
  PENDIENTE = 'PENDIENTE',
  OCUPADO = 'OCUPADO',
  LIBRE = 'LIBRE'
}

export enum TipoLocal {
  COMIDA = 'COMIDA',
  ROPA = 'ROPA',
  ELECTRODOMESTICOS = 'ELECTRODOMESTICOS',
  FARMACIA = 'FARMACIA',
  SERVICIOS = 'SERVICIOS',
  CARNICERIA = 'CARNICERIA',
  OTROS = 'OTROS'
}

export enum BluetoothConnectionState {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  RECONNECTING = 'RECONNECTING',
  ERROR = 'ERROR'
}

export enum BluetoothError {
  BLUETOOTH_DISABLED = 'BLUETOOTH_DISABLED',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PRINT_FAILED = 'PRINT_FAILED',
  TIMEOUT = 'TIMEOUT',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
